temp wip. delete repo l8r.
Signed-off-by: brian avery <brian.avery@intel.com>

diff --git a/ocf/nova-conductor b/ocf/nova-conductor
--- a/ocf/nova-conductor
+++ b/ocf/nova-conductor
@@ -1,11 +1,12 @@
 #!/bin/sh
 #
 #
-# OpenStack Orchestration Engine Service (heat-engine)
+# OpenStack Conductor Service (nova-conductor)
 #
-# Description:  Manages an OpenStack Orchestration Engine Service (heat-engine) process as an HA resource
+# Description:  Manages an OpenStack Conductor Service (nova-conductor) process as an HA resource
 #
-# Authors:      Emilien Macchi
+# Authors:      Sébastien Han
+# Mainly inspired by the Glance API resource agent written by Martin Gerhard Loschwitz from Hastexo: http://goo.gl/whLpr
 #
 # Support:      openstack@lists.launchpad.net
 # License:      Apache Software License (ASL) 2.0
@@ -37,9 +38,9 @@
 
 # Fill in some defaults if no values are specified
 
-OCF_RESKEY_binary_default="heat-engine"
-OCF_RESKEY_config_default="/etc/heat/heat.conf"
-OCF_RESKEY_user_default="heat"
+OCF_RESKEY_binary_default="nova-conductor"
+OCF_RESKEY_config_default="/etc/nova/nova.conf"
+OCF_RESKEY_user_default="nova"
 OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"
 OCF_RESKEY_database_server_port_default="3306"
 OCF_RESKEY_amqp_server_port_default="5672"
@@ -59,14 +60,14 @@ usage() {
     cat <<UEND
         usage: $0 (start|stop|validate-all|meta-data|status|monitor)
 
-        $0 manages an OpenStack Orchestration Engine Service (heat-engine) process as an HA resource 
+        $0 manages an OpenStack ConductorService (nova-conductor) process as an HA resource 
 
-        The 'start' operation starts the heat-engine service.
-        The 'stop' operation stops the heat-engine service.
+        The 'start' operation starts the conductor service.
+        The 'stop' operation stops the conductor service.
         The 'validate-all' operation reports whether the parameters are valid
         The 'meta-data' operation reports this RA's meta-data information
-        The 'status' operation reports whether the heat-engine service is running
-        The 'monitor' operation reports whether the heat-engine service seems to be working
+        The 'status' operation reports whether the conductor service is running
+        The 'monitor' operation reports whether the conductor service seems to be working
 
 UEND
 }
@@ -75,46 +76,46 @@ meta_data() {
     cat <<END
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-<resource-agent name="heat-engine">
+<resource-agent name="nova-conductor">
 <version>1.0</version>
 
 <longdesc lang="en">
-Resource agent for the OpenStack Orchestration Engine Service (heat-engine)
-May manage a heat-engine instance or a clone set that 
-creates a distributed heat-engine cluster.
+Resource agent for the OpenStack Nova Conductor Service (nova-conductor)
+May manage a nova-conductor instance or a clone set that 
+creates a distributed nova-conductor cluster.
 </longdesc>
-<shortdesc lang="en">Manages the OpenStack Orchestration Engine Service (heat-engine)</shortdesc>
+<shortdesc lang="en">Manages the OpenStack Conductor Service (nova-conductor)</shortdesc>
 <parameters>
 
 <parameter name="binary" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Orchestration Engine server binary (heat-engine)
+Location of the OpenStack Nova Conductor server binary (nova-conductor)
 </longdesc>
-<shortdesc lang="en">OpenStack Orchestration Engine server binary (heat-engine)</shortdesc>
+<shortdesc lang="en">OpenStack Nova Conductor server binary (nova-conductor)</shortdesc>
 <content type="string" default="${OCF_RESKEY_binary_default}" />
 </parameter>
 
 <parameter name="config" unique="0" required="0">
 <longdesc lang="en">
-Location of the OpenStack Orchestration Engine Service (heat-engine) configuration file
+Location of the OpenStack Conductor Service (nova-conductor) configuration file
 </longdesc>
-<shortdesc lang="en">OpenStack Orchestration Engine (heat-engine) config file</shortdesc>
+<shortdesc lang="en">OpenStack Nova Conductor (nova-conductor) config file</shortdesc>
 <content type="string" default="${OCF_RESKEY_config_default}" />
 </parameter>
 
 <parameter name="user" unique="0" required="0">
 <longdesc lang="en">
-User running OpenStack Orchestration Engine Service (heat-engine)
+User running OpenStack Conductor Service (nova-conductor)
 </longdesc>
-<shortdesc lang="en">OpenStack Orchestration Engine Service (heat-engine) user</shortdesc>
+<shortdesc lang="en">OpenStack Conductor Service (nova-conductor) user</shortdesc>
 <content type="string" default="${OCF_RESKEY_user_default}" />
 </parameter>
 
 <parameter name="pid" unique="0" required="0">
 <longdesc lang="en">
-The pid file to use for this OpenStack Orchestration Engine Service (heat-engine) instance
+The pid file to use for this OpenStack Conductor Service (nova-conductor) instance
 </longdesc>
-<shortdesc lang="en">OpenStack Orchestration Engine Service (heat-engine) pid file</shortdesc>
+<shortdesc lang="en">OpenStack Conductor Service (nova-conductor) pid file</shortdesc>
 <content type="string" default="${OCF_RESKEY_pid_default}" />
 </parameter>
 
@@ -144,9 +145,9 @@ If zeromq is used, this will disable the connection test to the AMQP server. Use
 
 <parameter name="additional_parameters" unique="0" required="0">
 <longdesc lang="en">
-Additional parameters to pass on to the OpenStack Orchestration Engine Service (heat-engine)
+Additional parameters to pass on to the OpenStack Conductor Service (nova-conductor)
 </longdesc>
-<shortdesc lang="en">Additional parameters for heat-engine</shortdesc>
+<shortdesc lang="en">Additional parameters for nova-conductor</shortdesc>
 <content type="string" />
 </parameter>
 
@@ -167,7 +168,7 @@ END
 #######################################################################
 # Functions invoked by resource manager actions
 
-heat_engine_check_port() {
+nova_conductor_check_port() {
 # This function has been taken from the squid RA and improved a bit
 # The length of the integer must be 4
 # Examples of valid port: "1080", "0080"
@@ -186,13 +187,13 @@ heat_engine_check_port() {
     fi
 }
 
-heat_engine_validate() {
+nova_conductor_validate() {
     local rc
 
     check_binary $OCF_RESKEY_binary
     check_binary netstat
-    heat_engine_check_port $OCF_RESKEY_database_server_port
-    heat_engine_check_port $OCF_RESKEY_amqp_server_port
+    nova_conductor_check_port $OCF_RESKEY_database_server_port
+    nova_conductor_check_port $OCF_RESKEY_amqp_server_port
     
     # A config file on shared storage that is not available
     # during probes is OK.
@@ -214,12 +215,12 @@ heat_engine_validate() {
     true
 }
 
-heat_engine_status() {
+nova_conductor_status() {
     local pid
     local rc
 
     if [ ! -f $OCF_RESKEY_pid ]; then
-        ocf_log info "OpenStack Orchestration Engine (heat-engine) is not running"
+        ocf_log info "OpenStack Nova Conductor (nova-conductor) is not running"
         return $OCF_NOT_RUNNING
     else
         pid=`cat $OCF_RESKEY_pid`
@@ -230,39 +231,33 @@ heat_engine_status() {
     if [ $rc -eq 0 ]; then
         return $OCF_SUCCESS
     else
-        ocf_log info "Old PID file found, but OpenStack Orchestration Engine (heat-engine) is not running"
+        ocf_log info "Old PID file found, but OpenStack Nova Conductor (nova-conductor) is not running"
         rm -f $OCF_RESKEY_pid
         return $OCF_NOT_RUNNING
     fi
 }
 
-# Function to check a process for port usage, as well as children
 check_port() {
     local port=$1
     local pid=$2
-
-    local children=`ps -ef | awk -v ppid=$pid '$3 == ppid { print $2}'`
-
-    for p in $pid $children
-    do
-        netstat -punt | grep -s "$port" | grep -s "$p" | grep -qs "ESTABLISHED"
-        if [ $? -eq 0 ]
-        then
-            return 0
-        fi
-    done
-    return 1
+    netstat -punt | grep -s "$port" | grep -s "$pid" | grep -qs "ESTABLISHED"
+    rc=$?
+    if [ $rc -eq 0 ]; then
+        return 0
+    else
+        return 1
+    fi
 }
 
-heat_engine_monitor() {
+nova_conductor_monitor() {
     local rc
     local pid
     local rc_db
     local rc_amqp
-    local engine_db_check
-    local engine_amqp_check
+    local conductor_db_check
+    local conductor_amqp_check
 
-    heat_engine_status
+    nova_conductor_status
     rc=$?
 
     # If status returned anything but success, return that immediately
@@ -271,63 +266,81 @@ heat_engine_monitor() {
     fi
 
     # Check the connections according to the PID.
-    # We are sure to hit the heat-engine process and not other heat process with the same connection behavior (for example heat-api)
+    # We are sure to hit the conductor process and not other nova process with the same connection behavior (for example nova-cert)
     if ocf_is_true "$OCF_RESKEY_zeromq"; then
-	    pid=`cat $OCF_RESKEY_pid`
-            engine_db_check=`check_port "$OCF_RESKEY_database_server_port" "$pid"`
-	    rc_db=$?
-	    if [ $rc_db -ne 0 ]; then
-	        ocf_log err "heat-engine is not connected to the database server: $rc_db"
-	        return $OCF_NOT_RUNNING
-	    fi
-	else
         pid=`cat $OCF_RESKEY_pid`
-        engine_db_check=`check_port "$OCF_RESKEY_database_server_port" "$pid"`
-        rc_db=$?
-        engine_amqp_check=`check_port "$OCF_RESKEY_amqp_server_port" "$pid"`
-        rc_amqp=$?
-	    if [ $rc_amqp -ne 0 ] || [ $rc_db -ne 0 ]; then
-	        ocf_log err "Heat Engine is not connected to the AMQP server and/or the database server: AMQP connection test returned $rc_amqp and database connection test returned $rc_db"
-	        return $OCF_NOT_RUNNING
-	    fi
-	fi
+        rc_db=`check_port $OCF_RESKEY_database_server_port $pid`
+        if [ $rc_db -ne 0 ]; then
+            ocf_log err "Nova Conductor is not connected to the database server: $rc_db"
+            return $OCF_NOT_RUNNING
+        fi
+    else
+        pid=`cat $OCF_RESKEY_pid`
+        rc_db=`check_port $OCF_RESKEY_database_server_port $pid`
+        rc_amqp=`check_port $OCF_RESKEY_amqp_server_port $pid`
+        if [ $rc_amqp -ne 0 ] || [ $rc_db -ne 0 ]; then
+            # may have multiple workers, in which case $pid is the parent and we want to check the children
+            # If there are no children or at least one child is not connected to both DB and AMQP then we fail.
+            KIDPIDS=`pgrep -P $pid -f nova-conductor`
+            if [ ! -z "$KIDPIDS" ]; then
+                for pid in $KIDPIDS
+                do
+                    rc_db=`check_port $OCF_RESKEY_database_server_port $pid`
+                    rc_amqp=`check_port $OCF_RESKEY_amqp_server_port $pid`
+                    if [ $rc_amqp -ne 0 ] || [ $rc_db -ne 0 ]; then
+                        ocf_log err "Nova Conductor pid $pid is not connected to the AMQP server and/or the database server: AMQP connection test returned $rc_amqp and database connection test returned $rc_db"
+                        return $OCF_NOT_RUNNING
+                    fi
+                done
+            else
+                ocf_log err "Nova Conductor pid $pid is not connected to the AMQP server and/or the database server: AMQP connection test returned $rc_amqp and database connection test returned $rc_db"
+                return $OCF_NOT_RUNNING
+            fi
+        fi
+    fi
 
-    ocf_log debug "OpenStack Orchestration Engine (heat-engine) monitor succeeded"
+    ocf_log debug "OpenStack Nova Conductor (nova-conductor) monitor succeeded"
     return $OCF_SUCCESS
 }
 
-heat_engine_start() {
+nova_conductor_start() {
     local rc
 
-    heat_engine_status
+    nova_conductor_status
     rc=$?
     if [ $rc -eq $OCF_SUCCESS ]; then
-        ocf_log info "OpenStack Orchestration Engine (heat-engine) already running"
+        ocf_log info "OpenStack Nova Conductor (nova-conductor) already running"
         return $OCF_SUCCESS
     fi
 
-    # run the actual heat-engine daemon. Don't use ocf_run as we're sending the tool's output
+    # Change the working dir to /, to be sure it's accesible
+    cd /
+
+    # Run the pre-start hooks.  This can be used to trigger a nova database sync, for example.
+    /usr/bin/nova-controller-runhooks
+
+    # run the actual nova-conductor daemon. Don't use ocf_run as we're sending the tool's output
     # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
     su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary} --config-file=$OCF_RESKEY_config \
        $OCF_RESKEY_additional_parameters"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid
 
     # Spin waiting for the server to come up.
     while true; do
-    heat_engine_monitor
+    nova_conductor_monitor
     rc=$?
     [ $rc -eq $OCF_SUCCESS ] && break
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
-        ocf_log err "OpenStack Orchestration Engine (heat-engine) start failed"
+        ocf_log err "OpenStack Nova Conductor (nova-conductor) start failed"
         exit $OCF_ERR_GENERIC
     fi
     sleep 1
     done
 
-    ocf_log info "OpenStack Orchestration Engine (heat-engine) started"
+    ocf_log info "OpenStack Nova Conductor (nova-conductor) started"
     return $OCF_SUCCESS
 }
 
-heat_engine_confirm_stop() {
+nova_conductor_confirm_stop() {
     local my_bin
     local my_processes
 
@@ -341,15 +354,15 @@ heat_engine_confirm_stop() {
     fi
 }
 
-heat_engine_stop() {
+nova_conductor_stop() {
     local rc
     local pid
 
-    heat_engine_status
+    nova_conductor_status
     rc=$?
     if [ $rc -eq $OCF_NOT_RUNNING ]; then
-        ocf_log info "OpenStack Orchestration Engine (heat-engine) already stopped"
-        heat_engine_confirm_stop
+        ocf_log info "OpenStack Nova Conductor (nova-conductor) already stopped"
+        nova_conductor_confirm_stop
         return $OCF_SUCCESS
     fi
 
@@ -358,8 +371,8 @@ heat_engine_stop() {
     ocf_run kill -s TERM $pid
     rc=$?
     if [ $rc -ne 0 ]; then
-        ocf_log err "OpenStack Orchestration Engine (heat-engine) couldn't be stopped"
-        heat_engine_confirm_stop
+        ocf_log err "OpenStack Nova Conductor (nova-conductor) couldn't be stopped"
+        nova_conductor_confirm_stop
         exit $OCF_ERR_GENERIC
     fi
 
@@ -370,27 +383,27 @@ heat_engine_stop() {
     fi
     count=0
     while [ $count -lt $shutdown_timeout ]; do
-        heat_engine_status
+        nova_conductor_status
         rc=$?
         if [ $rc -eq $OCF_NOT_RUNNING ]; then
             break
         fi
         count=`expr $count + 1`
         sleep 1
-        ocf_log debug "OpenStack Orchestration Engine (heat-engine) still hasn't stopped yet. Waiting ..."
+        ocf_log debug "OpenStack Nova Conductor (nova-conductor) still hasn't stopped yet. Waiting ..."
     done
 
-    heat_engine_status
+    nova_conductor_status
     rc=$?
     if [ $rc -ne $OCF_NOT_RUNNING ]; then
         # SIGTERM didn't help either, try SIGKILL
-        ocf_log info "OpenStack Orchestration Engine (heat-engine) failed to stop after ${shutdown_timeout}s \
+        ocf_log info "OpenStack Nova Conductor (nova-conductor) failed to stop after ${shutdown_timeout}s \
           using SIGTERM. Trying SIGKILL ..."
         ocf_run kill -s KILL $pid
     fi
-    heat_engine_confirm_stop
+    nova_conductor_confirm_stop
 
-    ocf_log info "OpenStack Orchestration Engine (heat-engine) stopped"
+    ocf_log info "OpenStack Nova Conductor (nova-conductor) stopped"
 
     rm -f $OCF_RESKEY_pid
 
@@ -407,15 +420,16 @@ case "$1" in
 esac
 
 # Anything except meta-data and help must pass validation
-heat_engine_validate || exit $?
+nova_conductor_validate || exit $?
 
 # What kind of method was invoked?
 case "$1" in
-  start)        heat_engine_start;;
-  stop)         heat_engine_stop;;
-  status)       heat_engine_status;;
-  monitor)      heat_engine_monitor;;
+  start)        nova_conductor_start;;
+  stop)         nova_conductor_stop;;
+  status)       nova_conductor_status;;
+  monitor)      nova_conductor_monitor;;
   validate-all) ;;
   *)            usage
                 exit $OCF_ERR_UNIMPLEMENTED;;
 esac
+
